name: Create and publish
on:
  push:
    branches:
    - master
    tags:
    - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/tibber-meter-uploader

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
       
      - name: Move jar file
        run: mkdir staging && cp target/*.jar staging/tibber-meter-uploader.${{ github.ref_name }}.jar

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          path: staging

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: staging/tibber-meter-uploader.${{ github.ref_name }}.jar

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile-prebuilt
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
